apiVersion: v1
kind: Service
metadata:
  name: kafka-hs
  labels:
    component: kafka
spec:
  ports:
    - port: 9092
      name: client
    - port: 29092
      name: external
    - port: 9093
      name: internal
  clusterIP: None
  selector:
    component: kafka