apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      component: kafka
  serviceName: kafka-hs
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        component: kafka
    spec:
      containers:
        - name: sasstify-kafka
          image: sasstify/sasstify.kafka:1.0-SNAPSHOT
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: 'zk-cs:2181'
            - name: KAFKA_ZOOKEEPER_USER
              value: 'sasstify'
            - name: KAFKA_ZOOKEEPER_PASSWORD
              value: 'sasstify'
            - name: KAFKA_ZOOKEEPER_PROTOCOL
              value: 'SASL'
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: 'CLIENT:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: 'CLIENT'
            #- name: KAFKA_CLIENT_USERS
            #  value: 'sasstifyKafka'
            #- name: KAFKA_CLIENT_PASSWORD
            #  value: 'sasstifyKafka'
            #  TLS implementation is not done yet, it depends on centralizer artifact management component
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
          ports:
            - containerPort: 9092
              name: client
            - containerPort: 29092
              name: external
            - containerPort: 9093
              name: internal
          volumeMounts:
            - name: datadir
              mountPath: /var/sasstify/zookeeper/
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi